In [48]:
import pandas as pd
import numpy as np
import json
import ast

In [61]:
final_df = pd.read_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/hotels_infos.csv")

In [62]:
final_df

,city,hotels
0,Mont-Saint-Michel,"[{'hotel_city': 'Huisnes-sur-Mer', 'name': 'Es..."
1,Saint-Malo,"[{'hotel_city': 'Saint-Malo', 'name': 'Kyriad ..."
2,Bayeux,"[{'hotel_city': 'Bayeux', 'name': 'Ibis Budget..."
3,Le-Havre,"[{'hotel_city': 'Perret, Le Havre', 'name': 'T..."
4,Rouen,"[{'hotel_city': 'Rouen', 'name': 'ibis budget ..."
5,Paris,"[{'hotel_city': '6e arr., Paris', 'name': 'Hot..."
6,Amiens,"[{'hotel_city': 'Amiens', 'name': 'Ibis Budget..."
7,Lille,"[{'hotel_city': 'Centre de Lille, Lille', 'nam..."
8,Strasbourg,"[{'hotel_city': 'Strasbourg', 'name': 'Hôtel R..."
9,Chateau-du-Haut-Koenigsbourg,"[{'hotel_city': 'Orschwiller', 'name': 'Domain..."
10,Colmar,"[{'hotel_city': 'Colmar', 'name': 'Hôtel Maiso..."
11,Eguisheim,"[{'hotel_city': 'Eguisheim', 'name': 'Hotel SP..."
12,Besancon,"[{'hotel_city': 'Besançon', 'name': 'ibis Styl..."
13,Dijon,"[{'hotel_city': 'Dijon', 'name': 'Kyriad Hotel..."
14,Annecy,"[{'hotel_city': ""Centre-ville d'Annecy, Annecy..."
15,Grenoble,"[{'hotel_city': 'Grenoble', 'name': 'Studio in..."
16,Lyon,"[{'hotel_city': '7e arr., Lyon', 'name': 'Mama..."
17,Gorges-du-Verdon,"[{'hotel_city': 'Sainte-Croix-de-Verdon', 'nam..."
18,Bormes-les-Mimosas,"[{'hotel_city': 'Bormes-les-Mimosas', 'name': ..."
19,Cassis,"[{'hotel_city': 'Cassis', 'name': 'Cassis cent..."
20,Marseille,"[{'hotel_city': 'Euromed - La Joliette, Marsei..."
21,Aix-en-Provence,"[{'hotel_city': 'Aix-en-Provence', 'name': 'Ap..."
22,Avignon,"[{'hotel_city': 'Avignon', 'name': 'ibis budge..."
23,Uzes,"[{'hotel_city': 'Uzès', 'name': 'Hôtel Le SAIN..."
24,Nimes,"[{'hotel_city': 'Nîmes', 'name': 'hotelF1 Nîme..."
25,Aigues-Mortes,"[{'hotel_city': 'Aigues-Mortes', 'name': 'Arte..."
26,Saintes-Maries-de-la-Mer,[{'hotel_city': 'Les Saintes-Maries-de-la-Mer'...
27,Collioure,"[{'hotel_city': 'Collioure', 'name': 'Residenc..."
28,Carcassonne,"[{'hotel_city': 'Carcassonne', 'name': 'Tribe ..."
29,Ariege,"[{'hotel_city': 'Ax-les-Thermes', 'name': 'Mer..."
30,Toulouse,"[{'hotel_city': 'Centre de Toulouse, Toulouse'..."
31,Montauban,"[{'hotel_city': 'Montauban', 'name': 'Unisotel..."
32,Biarritz,"[{'hotel_city': 'Biarritz', 'name': 'Nemea App..."
33,Bayonne,"[{'hotel_city': 'Bayonne', 'name': 'ibis budge..."
34,La Rochelle,"[{'hotel_city': 'La Rochelle', 'name': 'ibis b..."

In [63]:
# 1. Reconvertir la string en vraie liste de dictionnaires (convertion des strings en objets Python)
final_df["hotels"] = final_df["hotels"].apply(ast.literal_eval)

In [64]:
final_df

,city,hotels
0,Mont-Saint-Michel,"[{'hotel_city': 'Huisnes-sur-Mer', 'name': 'Es..."
1,Saint-Malo,"[{'hotel_city': 'Saint-Malo', 'name': 'Kyriad ..."
2,Bayeux,"[{'hotel_city': 'Bayeux', 'name': 'Ibis Budget..."
3,Le-Havre,"[{'hotel_city': 'Perret, Le Havre', 'name': 'T..."
4,Rouen,"[{'hotel_city': 'Rouen', 'name': 'ibis budget ..."
5,Paris,"[{'hotel_city': '6e arr., Paris', 'name': 'Hot..."
6,Amiens,"[{'hotel_city': 'Amiens', 'name': 'Ibis Budget..."
7,Lille,"[{'hotel_city': 'Centre de Lille, Lille', 'nam..."
8,Strasbourg,"[{'hotel_city': 'Strasbourg', 'name': 'Hôtel R..."
9,Chateau-du-Haut-Koenigsbourg,"[{'hotel_city': 'Orschwiller', 'name': 'Domain..."
10,Colmar,"[{'hotel_city': 'Colmar', 'name': 'Hôtel Maiso..."
11,Eguisheim,"[{'hotel_city': 'Eguisheim', 'name': 'Hotel SP..."
12,Besancon,"[{'hotel_city': 'Besançon', 'name': 'ibis Styl..."
13,Dijon,"[{'hotel_city': 'Dijon', 'name': 'Kyriad Hotel..."
14,Annecy,"[{'hotel_city': 'Centre-ville d'Annecy, Annecy..."
15,Grenoble,"[{'hotel_city': 'Grenoble', 'name': 'Studio in..."
16,Lyon,"[{'hotel_city': '7e arr., Lyon', 'name': 'Mama..."
17,Gorges-du-Verdon,"[{'hotel_city': 'Sainte-Croix-de-Verdon', 'nam..."
18,Bormes-les-Mimosas,"[{'hotel_city': 'Bormes-les-Mimosas', 'name': ..."
19,Cassis,"[{'hotel_city': 'Cassis', 'name': 'Cassis cent..."
20,Marseille,"[{'hotel_city': 'Euromed - La Joliette, Marsei..."
21,Aix-en-Provence,"[{'hotel_city': 'Aix-en-Provence', 'name': 'Ap..."
22,Avignon,"[{'hotel_city': 'Avignon', 'name': 'ibis budge..."
23,Uzes,"[{'hotel_city': 'Uzès', 'name': 'Hôtel Le SAIN..."
24,Nimes,"[{'hotel_city': 'Nîmes', 'name': 'hotelF1 Nîme..."
25,Aigues-Mortes,"[{'hotel_city': 'Aigues-Mortes', 'name': 'Arte..."
26,Saintes-Maries-de-la-Mer,[{'hotel_city': 'Les Saintes-Maries-de-la-Mer'...
27,Collioure,"[{'hotel_city': 'Collioure', 'name': 'Residenc..."
28,Carcassonne,"[{'hotel_city': 'Carcassonne', 'name': 'Tribe ..."
29,Ariege,"[{'hotel_city': 'Ax-les-Thermes', 'name': 'Mer..."
30,Toulouse,"[{'hotel_city': 'Centre de Toulouse, Toulouse'..."
31,Montauban,"[{'hotel_city': 'Montauban', 'name': 'Unisotel..."
32,Biarritz,"[{'hotel_city': 'Biarritz', 'name': 'Nemea App..."
33,Bayonne,"[{'hotel_city': 'Bayonne', 'name': 'ibis budge..."
34,La Rochelle,"[{'hotel_city': 'La Rochelle', 'name': 'ibis b..."

In [65]:
# 2. Une ligne par hôtel
final_df = final_df.explode("hotels", ignore_index=True)

In [66]:
final_df

                  city                                             hotels
0    Mont-Saint-Michel  {'hotel_city': 'Huisnes-sur-Mer', 'name': 'Esc...
1    Mont-Saint-Michel  {'hotel_city': 'Huisnes-sur-Mer', 'name': 'Hor...
2    Mont-Saint-Michel  {'hotel_city': 'Beauvoir', 'name': 'Le Petit G...
3    Mont-Saint-Michel  {'hotel_city': 'Saint-Georges-de-Gréhaigne', '...
4    Mont-Saint-Michel  {'hotel_city': 'Saint-Georges-de-Gréhaigne', '...
..                 ...                                                ...
870        La Rochelle  {'hotel_city': 'Centre-ville de La Rochelle, L...
871        La Rochelle  {'hotel_city': 'La Rochelle', 'name': 'Hôtel I...
872        La Rochelle  {'hotel_city': 'Centre-ville de La Rochelle, L...
873        La Rochelle  {'hotel_city': 'Centre-ville de La Rochelle, L...
874        La Rochelle  {'hotel_city': 'Centre-ville de La Rochelle, L...

[875 rows x 2 columns]

In [67]:
# 3. Transformer chaque dictionnaire hôtel en colonnes
hotel_details = pd.json_normalize(final_df["hotels"])

In [68]:
final_df = pd.concat([final_df.drop(columns=["hotels"]), hotel_details], axis=1)

In [69]:
final_df

,city,hotel_city,name,price,score
0,Mont-Saint-Michel,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé..."
1,Mont-Saint-Michel,Huisnes-sur-Mer,Horizon du Mont 15 personnes,€ 1 140,"Avec une note de 9,7 9,7 Exceptionnel 10 expér..."
2,Mont-Saint-Michel,Beauvoir,Le Petit Gîte du Mont,€ 440,"Avec une note de 8,9 8,9 Superbe 55 expérience..."
3,Mont-Saint-Michel,Saint-Georges-de-Gréhaigne,Ibis Budget Pontorson Baie Du Mont Saint Michel,€ 235,"Avec une note de 8,3 8,3 Très bien 670 expérie..."
4,Mont-Saint-Michel,Saint-Georges-de-Gréhaigne,ibis Pontorson Baie Du Mont Saint Michel,€ 267,"Avec une note de 7,9 7,9 Bien 2 892 expérience..."
...,...,...,...,...,...
870,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",IBIS La Rochelle Vieux Port Centre,€ 239,"Avec une note de 8,5 8,5 Très bien 1 007 expér..."
871,La Rochelle,La Rochelle,Hôtel Inn Design La Rochelle,€ 165,"Avec une note de 7,9 7,9 Bien 3 252 expérience..."
872,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",Superbe appartement avec parking,€ 381,"Avec une note de 8,9 8,9 Superbe 42 expérience..."
873,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",Hôtel Les Gens de Mer La Rochelle,€ 202,"Avec une note de 7,8 7,8 Bien 2 045 expérience..."
874,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",Escale Pamatxi : Vieux port,€ 237,"Avec une note de 8,6 8,6 Superbe 72 expérience..."

In [54]:
hotel_details

,hotel_city,name,price,score
0,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé..."
1,Huisnes-sur-Mer,Horizon du Mont 15 personnes,€ 1 140,"Avec une note de 9,7 9,7 Exceptionnel 10 expér..."
2,Beauvoir,Le Petit Gîte du Mont,€ 440,"Avec une note de 8,9 8,9 Superbe 55 expérience..."
3,Saint-Georges-de-Gréhaigne,Ibis Budget Pontorson Baie Du Mont Saint Michel,€ 235,"Avec une note de 8,3 8,3 Très bien 670 expérie..."
4,Saint-Georges-de-Gréhaigne,ibis Pontorson Baie Du Mont Saint Michel,€ 267,"Avec une note de 7,9 7,9 Bien 2 892 expérience..."
...,...,...,...,...
870,"Centre-ville de La Rochelle, La Rochelle",IBIS La Rochelle Vieux Port Centre,€ 239,"Avec une note de 8,5 8,5 Très bien 1 007 expér..."
871,La Rochelle,Hôtel Inn Design La Rochelle,€ 165,"Avec une note de 7,9 7,9 Bien 3 252 expérience..."
872,"Centre-ville de La Rochelle, La Rochelle",Superbe appartement avec parking,€ 381,"Avec une note de 8,9 8,9 Superbe 42 expérience..."
873,"Centre-ville de La Rochelle, La Rochelle",Hôtel Les Gens de Mer La Rochelle,€ 202,"Avec une note de 7,8 7,8 Bien 2 045 expérience..."
874,"Centre-ville de La Rochelle, La Rochelle",Escale Pamatxi : Vieux port,€ 237,"Avec une note de 8,6 8,6 Superbe 72 expérience..."