In [1]:
import pandas as pd
import numpy as np
import json
import ast

In [ ]:
# Nettoyage du dataframe et Normalisation de la colonne Hotels pour préparer le dataset final pour l'EDA.

In [2]:
final_df = pd.read_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/hotels_infos.csv")

In [3]:
# Reconvertir la string en vraie liste de dictionnaires (convertion des strings en objets Python)
final_df["hotels"] = final_df["hotels"].apply(ast.literal_eval)

In [4]:
# Une ligne par hôtel
final_df = final_df.explode("hotels", ignore_index=True)

In [5]:
# Transformer chaque dictionnaire hôtel en colonnes
hotel_details = pd.json_normalize(final_df["hotels"])

In [6]:
hotel_details = pd.concat([final_df.drop(columns=["hotels"]), hotel_details], axis=1)

In [7]:
hotel_details

,city,hotel_city,name,price,score
0,Mont-Saint-Michel,Huisnes-sur-Mer,Escale du Mont,€ 364,"Avec une note de 7,5 7,5 Bien 2 expériences vé..."
1,Mont-Saint-Michel,Huisnes-sur-Mer,Horizon du Mont 15 personnes,€ 1 140,"Avec une note de 9,7 9,7 Exceptionnel 10 expér..."
2,Mont-Saint-Michel,Beauvoir,Le Petit Gîte du Mont,€ 440,"Avec une note de 8,9 8,9 Superbe 55 expérience..."
3,Mont-Saint-Michel,Saint-Georges-de-Gréhaigne,Ibis Budget Pontorson Baie Du Mont Saint Michel,€ 235,"Avec une note de 8,3 8,3 Très bien 670 expérie..."
4,Mont-Saint-Michel,Saint-Georges-de-Gréhaigne,ibis Pontorson Baie Du Mont Saint Michel,€ 267,"Avec une note de 7,9 7,9 Bien 2 892 expérience..."
...,...,...,...,...,...
870,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",IBIS La Rochelle Vieux Port Centre,€ 239,"Avec une note de 8,5 8,5 Très bien 1 007 expér..."
871,La Rochelle,La Rochelle,Hôtel Inn Design La Rochelle,€ 165,"Avec une note de 7,9 7,9 Bien 3 252 expérience..."
872,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",Superbe appartement avec parking,€ 381,"Avec une note de 8,9 8,9 Superbe 42 expérience..."
873,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",Hôtel Les Gens de Mer La Rochelle,€ 202,"Avec une note de 7,8 7,8 Bien 2 045 expérience..."
874,La Rochelle,"Centre-ville de La Rochelle, La Rochelle",Escale Pamatxi : Vieux port,€ 237,"Avec une note de 8,6 8,6 Superbe 72 expérience..."

In [8]:
hotel_details['name'] = hotel_details['name'].str.split(' - ').str[0] # register hotel label
hotel_details['rate'] = hotel_details['score'].str.extract(r'(?:de\s+)?(\d+(?:,\d+)?)') # extract hotel score  
hotel_details['rate_label'] = hotel_details['score'].str.extract(r'(?:\d+(?:,\d+)?)\s+(?:\d+(?:,\d+)?)\s+([^\d]+?)\s+\d+')[0].str.strip() # extract rate label
hotel_details['experience'] = hotel_details['score'].str.extract(r'(\d+(?:\s+\d+)*)\s+expériences?')[0] # extract number of experiences
hotel_details['hotel_city'] = hotel_details['hotel_city'].str.split(',').str[-1].str.strip() # extract hotel city

In [9]:
hotel_details = hotel_details.drop(columns=['score'])

In [10]:
hotel_details

,city,hotel_city,name,price,rate,rate_label,experience
0,Mont-Saint-Michel,Huisnes-sur-Mer,Escale du Mont,€ 364,"7,5",Bien,2
1,Mont-Saint-Michel,Huisnes-sur-Mer,Horizon du Mont 15 personnes,€ 1 140,"9,7",Exceptionnel,10
2,Mont-Saint-Michel,Beauvoir,Le Petit Gîte du Mont,€ 440,"8,9",Superbe,55
3,Mont-Saint-Michel,Saint-Georges-de-Gréhaigne,Ibis Budget Pontorson Baie Du Mont Saint Michel,€ 235,"8,3",Très bien,670
4,Mont-Saint-Michel,Saint-Georges-de-Gréhaigne,ibis Pontorson Baie Du Mont Saint Michel,€ 267,"7,9",Bien,2 892
...,...,...,...,...,...,...,...
870,La Rochelle,La Rochelle,IBIS La Rochelle Vieux Port Centre,€ 239,"8,5",Très bien,1 007
871,La Rochelle,La Rochelle,Hôtel Inn Design La Rochelle,€ 165,"7,9",Bien,3 252
872,La Rochelle,La Rochelle,Superbe appartement avec parking,€ 381,"8,9",Superbe,42
873,La Rochelle,La Rochelle,Hôtel Les Gens de Mer La Rochelle,€ 202,"7,8",Bien,2 045
874,La Rochelle,La Rochelle,Escale Pamatxi : Vieux port,€ 237,"8,6",Superbe,72