In [1]:
# Import des librairies pour l'EDA de Kayak
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
final_df = pd.read_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/final_data_test.csv")

In [3]:
pd.set_option('display.max_columns', None)
final_df

,city,place_id,lat,lon,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,clouds.all,sys.country,sys.sunrise,sys.sunset,sys.type,sys.id,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotels
0,mont saint michel,285390554,48.635954,-1.511460,stations,10000,1787833888,7200,6435453,Huisnes-sur-Mer,200,-1.5115,48.6360,24.25,24.01,24.25,24.25,1009,49,1009,1003,3.31,261,5.58,99,FR,1787807759,1787857183,NaN,NaN,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Rose', 'price': '€ 313', 'sco..."
1,saint malo,284423924,48.649518,-2.026041,stations,10000,1787833889,7200,2978640,Saint-Malo,200,-2.0260,48.6495,23.29,23.24,23.21,23.29,1009,60,1009,1007,3.09,0,NaN,100,FR,1787807882,1787857308,1.0,6557.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Kyriad Prestige Saint-Malo', 'price..."
2,bayeux,280655053,49.276462,-0.702474,stations,7429,1787833891,7200,3034483,Bayeux,200,-0.7025,49.2765,25.14,25.33,25.14,25.14,1009,62,1009,1003,1.34,84,1.51,100,FR,1787807496,1787857058,1.0,6569.0,NaN,804,Clouds,couvert,04d,"[{'name': 'B&B HOTEL Bayeux', 'price': '€ 241'..."
3,le havre,100021883,49.493898,0.107973,stations,10000,1787833862,7200,3003796,Havre-de-Grâce,200,0.1135,49.4884,23.55,23.74,23.55,24.90,1009,68,1009,1007,4.63,230,NaN,100,FR,1787807277,1787856886,1.0,6533.0,NaN,804,Clouds,couvert,04d,[{'name': 'Les Beaux Volumes - Grand T2 rénové...
4,rouen,99438300,49.440459,1.093966,stations,10000,1787833893,7200,6454707,Rouen,200,1.0940,49.4405,25.58,25.71,24.60,26.44,1009,58,1009,997,4.63,210,NaN,100,FR,1787807046,1787856646,2.0,2003589.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Grand Hôtel De La Seine', 'price': ..."
5,paris,97347287,48.853495,2.348391,stations,10000,1787833439,7200,2968815,Paris,200,2.3488,48.8534,26.24,26.24,25.10,27.92,1010,61,1010,1000,2.24,197,3.13,91,FR,1787806809,1787856281,2.0,2012208.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Ibis Styles Paris Batignolles', 'pr..."
6,amiens,99360340,49.894171,2.295695,stations,10000,1787833895,7200,3037854,Amiens,200,2.2957,49.8942,27.66,28.32,27.66,27.66,1008,53,1008,998,3.96,233,6.91,100,FR,1787806707,1787856408,NaN,NaN,NaN,804,Clouds,couvert,04d,"[{'name': 'Ibis Budget Amiens Centre Gare', 'p..."
7,lille,101870667,50.636565,3.063528,stations,10000,1787833896,7200,2998324,Lille,200,3.0635,50.6366,28.40,29.45,26.66,29.38,1008,55,1008,1004,4.63,220,NaN,100,FR,1787806438,1787856309,2.0,2011132.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Babel Lille Centre', 'price': '€ 25..."
8,strasbourg,120878363,48.584614,7.750713,stations,10000,1787833897,7200,2973781,Strasbourg,200,7.7507,48.5846,31.53,31.46,30.72,33.62,1011,39,1011,995,1.39,157,1.54,100,FR,1787805540,1787854957,2.0,18926.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Hôtel Restaurant Athena Spa', 'pric..."
9,chateau du haut koenigsbourg,121188411,48.249382,7.343941,stations,10000,1787833898,7200,6441605,Saint-Hippolyte,200,7.3439,48.2494,26.90,27.21,26.90,27.24,1011,48,1011,965,1.03,0,NaN,100,FR,1787805673,1787855020,1.0,6482.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Domaine du Haut-Koenigsbourg', 'pri..."
10,colmar,120649250,48.077752,7.357964,stations,10000,1787833791,7200,3024297,Colmar,200,7.3580,48.0778,30.09,31.18,29.94,31.70,1011,50,1011,971,2.00,196,4.50,83,FR,1787805688,1787854998,1.0,6482.0,NaN,803,Clouds,nuageux,04d,"[{'name': 'Hôtel Maison Turenne', 'price': '€ ..."
11,eguisheim,121083240,48.044797,7.307962,stations,10000,1787833901,7200,3020324,Eguisheim,200,7.3080,48.0448,30.07,31.15,29.21,30.24,1011,50,1011,968,1.03,0,NaN,99,FR,1787805703,1787855007,5.0,50014460.0,NaN,804,Clouds,couvert,04d,[{'name': 'Hotel SPA Restaurant Husseren Colle...
12,besancon,92553994,47.238022,6.024362,stations,10000,1787833825,7200,3033123,Besançon,200,6.0247,47.2432,30.51,31.65,30.14,31.95,1011,49,1011,972,3.04,246,4.12,100,FR,1787806093,1787855232,5.0,50014141.0,NaN,804,Clouds,couvert,04d,[{'name': 'Premiere Classe Besancon Ecole Vale...
13,dijon,93940430,47.321581,5.041470,stations,10000,1787833903,7200,3006622,Larrey,200,5.0415,47.3216,27.80,27.76,27.80,27.80,1011,44,1011,974,2.57,150,NaN,100,FR,1787806322,1787855476,1.0,6586.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Le Jacquemart', 'price': '€ 1..."
14,annecy,89628032,45.899235,6.128885,stations,10000,1787833891,7200,3037543,Annecy,200,6.1323,45.9008,29.08,29.18,29.08,29.08,1012,45,1012,928,1.03,0,NaN,60,FR,1787806199,1787855075,1.0,6500.0,NaN,803,Clouds,nuageux,04d,"[{'name': 'appartement moderne et spacieux, pa..."
15,grenoble,89727718,45.187560,5.735782,stations,10000,1787833905,7200,6454071,Grenoble,200,5.7358,45.1876,33.76,35.02,33.76,33.76,1011,40,1011,919,4.92,157,9.83,100,FR,1787806362,1787855103,2.0,2004515.0,NaN,804,Clouds,couvert,04d,[{'name': 'B&B HOTEL Grenoble Centre Verlaine'...
16,lyon,90359235,45.757814,4.832011,stations,10000,1787833692,7200,8015556,Vieux Lyon,200,4.8320,45.7578,32.87,34.72,31.27,33.46,1010,45,1010,980,12.86,190,NaN,99,FR,1787806525,1787855373,1.0,6505.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Mama Shelter Lyon', 'price': '€ 276..."
17,gorges du verdon,82363223,43.749656,6.328562,stations,10000,1787833907,7200,6451459,Bauduen,200,6.3286,43.7497,26.65,26.65,26.65,26.65,1016,53,1016,918,3.84,138,5.23,98,FR,1787806349,1787854830,2.0,2006427.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Le 10 18 hôtel restaurant', 'price'..."
18,bormes les mimosas,81776233,43.150697,6.341928,stations,10000,1787833908,7200,3031532,Bormes-les-Mimosas,200,6.3419,43.1507,28.91,32.71,28.47,30.76,1015,71,1015,998,4.92,61,9.39,100,FR,1787806398,1787854775,2.0,2006377.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel La Voile', 'price': '€ 287', ..."
19,cassis,83165753,43.214036,5.539632,stations,10000,1787833909,7200,3028431,Cassis,200,5.5396,43.2140,32.54,37.72,31.27,33.56,1012,58,1012,1002,0.45,124,2.68,96,FR,1787806586,1787854973,2.0,2012554.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Le Golfe', 'price': '€ 306', ..."
20,marseille,83395174,43.296399,5.377789,stations,10000,1787833911,7200,2995469,Marseille,200,5.3778,43.2964,31.56,34.50,31.30,33.87,1012,54,1012,1006,3.58,81,6.26,89,FR,1787806617,1787855019,2.0,80238.0,NaN,804,Clouds,couvert,04d,[{'name': 'MEININGER Marseille Centre la Jolie...
21,aix en provence,83161830,43.529842,5.447474,stations,10000,1787833912,7200,3038354,Aix-en-Provence,200,5.4475,43.5298,31.53,33.97,30.14,33.07,1012,52,1012,981,2.68,169,5.36,100,FR,1787806580,1787855022,2.0,2006832.0,NaN,804,Clouds,couvert,04d,[{'name': 'Aparthotel Adagio Access Aix-en-Pro...
22,avignon,82758863,43.949249,4.805901,stations,10000,1787833335,7200,3035681,Avignon,200,4.8059,43.9493,33.81,37.03,33.05,34.57,1011,47,1011,1005,7.20,180,NaN,100,FR,1787806697,1787855213,2.0,2024181.0,NaN,804,Clouds,couvert,04d,"[{'name': 'ibis budget Avignon Centre', 'price..."
23,uzes,87602259,44.012128,4.419672,stations,10000,1787833914,7200,2971258,Uzès,200,4.4197,44.0121,31.78,35.45,29.71,31.78,1012,56,1012,995,8.94,176,10.89,100,FR,1787806785,1787855311,2.0,2024181.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Boutique Hôtel Entraigues', 'price'..."
24,nimes,83003654,43.837425,4.360069,stations,10000,1787833915,7200,2990363,Nîmes,200,4.3601,43.8374,30.22,35.58,30.22,30.22,1012,70,1012,1004,11.83,150,16.98,100,FR,1787806814,1787855310,1.0,6599.0,NaN,804,Clouds,couvert,04d,"[{'name': 'hotelF1 Nîmes Ouest', 'price': '€ 8..."
25,aigues mortes,83220284,43.566152,4.191540,stations,10000,1787833888,7200,6452244,Aigues-Mortes,200,4.1915,43.5662,26.98,30.58,26.98,27.77,1012,89,1012,1012,7.72,130,NaN,100,FR,1787806879,1787855327,1.0,6518.0,NaN,804,Clouds,couvert,04d,[{'name': 'Hôtel les jardins du canal - piscin...
26,saintes maries de la mer,83337373,43.451592,4.427720,stations,10000,1787833917,7200,6447171,Saintes-Maries-de-la-Mer,200,4.4277,43.4516,25.77,26.73,25.77,25.77,1012,89,1012,1012,11.90,136,15.22,100,FR,1787806832,1787855260,NaN,NaN,NaN,804,Clouds,couvert,04d,[{'name': 'Oh! Campings - La Brise de Camargue...
27,collioure,84564617,42.525050,3.083155,stations,10000,1787833918,7200,3024314,Collioure,200,3.0832,42.5251,35.45,37.44,31.70,36.18,1008,38,1008,988,8.63,159,13.65,31,FR,1787807235,1787855503,2.0,2036964.0,NaN,802,Clouds,partiellement nuageux,03d,"[{'name': ""Les Chênes-lièges d'Ambeille"", 'pri..."
28,carcassonne,85200361,43.213036,2.349107,stations,10000,1787833491,7200,3028641,Carcassonne,200,2.3534,43.2088,32.11,37.96,32.11,33.76,1007,62,1007,979,9.77,60,NaN,98,FR,1787807351,1787855736,1.0,6513.0,NaN,804,Clouds,couvert,04d,"[{'name': 'Tribe Carcassonne', 'price': '€ 286..."
29,ariege,84352446,42.945537,1.406554,stations,10000,1787833921,7200,3007059,Larbont,200,1.4066,42.9455,26.90,26.56,25.50,27.36,1009,35,1009,905,1.34,94,8.05,0,FR,1787807601,1787855940,2.0,2106908.0,NaN,800,Clear,ciel dégagé,01d,"[{'name': 'Mercure Ax Les Thermes', 'price': '..."
30,toulouse,85889491,43.604464,1.444243,stations,10000,1787833357,7200,2972315,Toulouse,200,1.4437,43.6043,31.99,33.23,31.99,32.55,1007,45,1007,987,3.60,140,NaN,58,FR,1787807535,1787855989,1.0,6467.0,NaN,803,Clouds,nuageux,04d,[{'name': 'Eklo Hotels Toulouse Cartoucherie Z...
31,montauban,85147342,44.017584,1.354999,stations,10000,1787833923,7200,2993002,Montauban,200,1.3550,44.0176,30.56,31.23,30.56,30.56,1008,46,1008,995,2.01,207,3.43,100,FR,1787807520,1787856046,NaN,NaN,NaN,804,Clouds,couvert,04d,"[{'name': 'Unisotel Montauban EX F1', 'price':..."
32,biarritz,291979173,43.471144,-1.552728,stations,10000,1787833924,7200,3032797,Biarritz,200,-1.5527,43.4711,23.00,23.03,22.55,23.00,1009,64,1009,1003,1.03,0,NaN,100,FR,1787808267,1787856695,1.0,6478.0,0.85,500,Rain,légère pluie,10d,[{'name': 'Nemea Appart Hotel Les Hauts de Mil...
33,bayonne,291698146,43.494514,-1.473666,stations,10000,1787833925,7200,3034475,Bayonne,200,-1.4737,43.4945,23.42,23.49,22.97,24.54,1009,64,1009,1005,1.03,0,NaN,100,FR,1787808246,1787856678,1.0,6478.0,1.41,501,Rain,pluie modérée,10d,"[{'name': 'ibis budget Bayonne', 'price': '€ 1..."
34,la rochelle,290369823,46.159732,-1.151595,stations,10000,1787833926,7200,3006787,La Rochelle,200,-1.1516,46.1597,20.21,20.40,20.07,20.74,1010,81,1010,1010,1.54,90,NaN,100,FR,1787807924,1787856846,1.0,6458.0,17.12,503,Rain,très forte pluie,10d,[{'name': 'ibis budget La Rochelle Centre les ...

In [4]:
# Nettoyage de données

In [5]:
df = final_df.copy()

In [6]:
print(type(df))
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
city                      0
place_id                  0
lat                       0
lon                       0
base                      0
visibility                0
dt                        0
timezone                  0
id                        0
name                      0
cod                       0
coord.lon                 0
coord.lat                 0
main.temp                 0
main.feels_like           0
main.temp_min             0
main.temp_max             0
main.pressure             0
main.humidity             0
main.sea_level            0
main.grnd_level           0
wind.speed                0
wind.deg                  0
wind.gust                16
clouds.all                0
sys.country               0
sys.sunrise               0
sys.sunset                0
sys.type                  4
sys.id                    4
rain.1h                  32
weather.0.id              0
weather.0.main            0
weather.0.description     0
weather.0.icon            0
hotels                    0
dtype: int64

Valeurs nulles : 
    wind.gust = 16 # => pas de rafales de vent enregistrées dans cette zone
    rain.1h = 32 # => pas de précipitations enregistrées dans cette zone
    # => pour ces valeurs, la valeur nulle correspond à un evenment qui n'a pas eu lieu, donc on peut les considérer comme des valeurs valides et les remplacer par 0. 

    sys.type = 4 # => info interne à openweathermap obsolète, on peut la supprimer
    sys.id = 4 # => info interne à openweathermap obsolète, on peut la supprimer

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   35 non-null     object
 1   place_id               35 non-null     int64
 2   lat                    35 non-null     float64
 3   lon                    35 non-null     float64
 4   base                   35 non-null     object
 5   visibility             35 non-null     int64
 6   dt                     35 non-null     int64
 7   timezone               35 non-null     int64
 8   id                     35 non-null     int64
 9   name                   35 non-null     object
 10  cod                    35 non-null     int64
 11  coord.lon              35 non-null     float64
 12  coord.lat              35 non-null     float64
 13  main.temp              35 non-null     float64
 14  main.feels_like        35 non-null     float64
 15  main.temp_min          35 non-null     float64
 16  main.temp_max          35 non-null     float64
 17  main.pressure          35 non-null     int64
 18  main.humidity          35 non-null     int64
 19  main.sea_level         35 non-null     int64
 20  main.grnd_level        35 non-null     int64
 21  wind.speed             35 non-null     float64
 22  wind.deg               35 non-null     int64
 23  wind.gust              19 non-null     float64
 24  clouds.all             35 non-null     int64
 25  sys.country            35 non-null     object
 26  sys.sunrise            35 non-null     int64
 27  sys.sunset             35 non-null     int64
 28  sys.type               31 non-null     float64
 29  sys.id                 31 non-null     float64
 30  rain.1h                3 non-null      float64
 31  weather.0.id           35 non-null     int64
 32  weather.0.main         35 non-null     object
 33  weather.0.description  35 non-null     object
 34  weather.0.icon         35 non-null     object
 35  hotels                 35 non-null     object
dtypes: float64(13), int64(15), object(8)
memory usage: 10.0+ KB

In [8]:
df = df.drop(columns=['sys.type', 'sys.id', "sys.country", "coord.lon", "coord.lat", "cod", "base", "name", "id", "timezone", "place_id"])

In [9]:
df

,city,lat,lon,visibility,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,clouds.all,sys.sunrise,sys.sunset,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotels
0,mont saint michel,48.635954,-1.511460,10000,1787833888,24.25,24.01,24.25,24.25,1009,49,1009,1003,3.31,261,5.58,99,1787807759,1787857183,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Rose', 'price': '€ 313', 'sco..."
1,saint malo,48.649518,-2.026041,10000,1787833889,23.29,23.24,23.21,23.29,1009,60,1009,1007,3.09,0,NaN,100,1787807882,1787857308,NaN,804,Clouds,couvert,04d,"[{'name': 'Kyriad Prestige Saint-Malo', 'price..."
2,bayeux,49.276462,-0.702474,7429,1787833891,25.14,25.33,25.14,25.14,1009,62,1009,1003,1.34,84,1.51,100,1787807496,1787857058,NaN,804,Clouds,couvert,04d,"[{'name': 'B&B HOTEL Bayeux', 'price': '€ 241'..."
3,le havre,49.493898,0.107973,10000,1787833862,23.55,23.74,23.55,24.90,1009,68,1009,1007,4.63,230,NaN,100,1787807277,1787856886,NaN,804,Clouds,couvert,04d,[{'name': 'Les Beaux Volumes - Grand T2 rénové...
4,rouen,49.440459,1.093966,10000,1787833893,25.58,25.71,24.60,26.44,1009,58,1009,997,4.63,210,NaN,100,1787807046,1787856646,NaN,804,Clouds,couvert,04d,"[{'name': 'Grand Hôtel De La Seine', 'price': ..."
5,paris,48.853495,2.348391,10000,1787833439,26.24,26.24,25.10,27.92,1010,61,1010,1000,2.24,197,3.13,91,1787806809,1787856281,NaN,804,Clouds,couvert,04d,"[{'name': 'Ibis Styles Paris Batignolles', 'pr..."
6,amiens,49.894171,2.295695,10000,1787833895,27.66,28.32,27.66,27.66,1008,53,1008,998,3.96,233,6.91,100,1787806707,1787856408,NaN,804,Clouds,couvert,04d,"[{'name': 'Ibis Budget Amiens Centre Gare', 'p..."
7,lille,50.636565,3.063528,10000,1787833896,28.40,29.45,26.66,29.38,1008,55,1008,1004,4.63,220,NaN,100,1787806438,1787856309,NaN,804,Clouds,couvert,04d,"[{'name': 'Babel Lille Centre', 'price': '€ 25..."
8,strasbourg,48.584614,7.750713,10000,1787833897,31.53,31.46,30.72,33.62,1011,39,1011,995,1.39,157,1.54,100,1787805540,1787854957,NaN,804,Clouds,couvert,04d,"[{'name': 'Hôtel Restaurant Athena Spa', 'pric..."
9,chateau du haut koenigsbourg,48.249382,7.343941,10000,1787833898,26.90,27.21,26.90,27.24,1011,48,1011,965,1.03,0,NaN,100,1787805673,1787855020,NaN,804,Clouds,couvert,04d,"[{'name': 'Domaine du Haut-Koenigsbourg', 'pri..."
10,colmar,48.077752,7.357964,10000,1787833791,30.09,31.18,29.94,31.70,1011,50,1011,971,2.00,196,4.50,83,1787805688,1787854998,NaN,803,Clouds,nuageux,04d,"[{'name': 'Hôtel Maison Turenne', 'price': '€ ..."
11,eguisheim,48.044797,7.307962,10000,1787833901,30.07,31.15,29.21,30.24,1011,50,1011,968,1.03,0,NaN,99,1787805703,1787855007,NaN,804,Clouds,couvert,04d,[{'name': 'Hotel SPA Restaurant Husseren Colle...
12,besancon,47.238022,6.024362,10000,1787833825,30.51,31.65,30.14,31.95,1011,49,1011,972,3.04,246,4.12,100,1787806093,1787855232,NaN,804,Clouds,couvert,04d,[{'name': 'Premiere Classe Besancon Ecole Vale...
13,dijon,47.321581,5.041470,10000,1787833903,27.80,27.76,27.80,27.80,1011,44,1011,974,2.57,150,NaN,100,1787806322,1787855476,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Le Jacquemart', 'price': '€ 1..."
14,annecy,45.899235,6.128885,10000,1787833891,29.08,29.18,29.08,29.08,1012,45,1012,928,1.03,0,NaN,60,1787806199,1787855075,NaN,803,Clouds,nuageux,04d,"[{'name': 'appartement moderne et spacieux, pa..."
15,grenoble,45.187560,5.735782,10000,1787833905,33.76,35.02,33.76,33.76,1011,40,1011,919,4.92,157,9.83,100,1787806362,1787855103,NaN,804,Clouds,couvert,04d,[{'name': 'B&B HOTEL Grenoble Centre Verlaine'...
16,lyon,45.757814,4.832011,10000,1787833692,32.87,34.72,31.27,33.46,1010,45,1010,980,12.86,190,NaN,99,1787806525,1787855373,NaN,804,Clouds,couvert,04d,"[{'name': 'Mama Shelter Lyon', 'price': '€ 276..."
17,gorges du verdon,43.749656,6.328562,10000,1787833907,26.65,26.65,26.65,26.65,1016,53,1016,918,3.84,138,5.23,98,1787806349,1787854830,NaN,804,Clouds,couvert,04d,"[{'name': 'Le 10 18 hôtel restaurant', 'price'..."
18,bormes les mimosas,43.150697,6.341928,10000,1787833908,28.91,32.71,28.47,30.76,1015,71,1015,998,4.92,61,9.39,100,1787806398,1787854775,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel La Voile', 'price': '€ 287', ..."
19,cassis,43.214036,5.539632,10000,1787833909,32.54,37.72,31.27,33.56,1012,58,1012,1002,0.45,124,2.68,96,1787806586,1787854973,NaN,804,Clouds,couvert,04d,"[{'name': 'Hotel Le Golfe', 'price': '€ 306', ..."
20,marseille,43.296399,5.377789,10000,1787833911,31.56,34.50,31.30,33.87,1012,54,1012,1006,3.58,81,6.26,89,1787806617,1787855019,NaN,804,Clouds,couvert,04d,[{'name': 'MEININGER Marseille Centre la Jolie...
21,aix en provence,43.529842,5.447474,10000,1787833912,31.53,33.97,30.14,33.07,1012,52,1012,981,2.68,169,5.36,100,1787806580,1787855022,NaN,804,Clouds,couvert,04d,[{'name': 'Aparthotel Adagio Access Aix-en-Pro...
22,avignon,43.949249,4.805901,10000,1787833335,33.81,37.03,33.05,34.57,1011,47,1011,1005,7.20,180,NaN,100,1787806697,1787855213,NaN,804,Clouds,couvert,04d,"[{'name': 'ibis budget Avignon Centre', 'price..."
23,uzes,44.012128,4.419672,10000,1787833914,31.78,35.45,29.71,31.78,1012,56,1012,995,8.94,176,10.89,100,1787806785,1787855311,NaN,804,Clouds,couvert,04d,"[{'name': 'Boutique Hôtel Entraigues', 'price'..."
24,nimes,43.837425,4.360069,10000,1787833915,30.22,35.58,30.22,30.22,1012,70,1012,1004,11.83,150,16.98,100,1787806814,1787855310,NaN,804,Clouds,couvert,04d,"[{'name': 'hotelF1 Nîmes Ouest', 'price': '€ 8..."
25,aigues mortes,43.566152,4.191540,10000,1787833888,26.98,30.58,26.98,27.77,1012,89,1012,1012,7.72,130,NaN,100,1787806879,1787855327,NaN,804,Clouds,couvert,04d,[{'name': 'Hôtel les jardins du canal - piscin...
26,saintes maries de la mer,43.451592,4.427720,10000,1787833917,25.77,26.73,25.77,25.77,1012,89,1012,1012,11.90,136,15.22,100,1787806832,1787855260,NaN,804,Clouds,couvert,04d,[{'name': 'Oh! Campings - La Brise de Camargue...
27,collioure,42.525050,3.083155,10000,1787833918,35.45,37.44,31.70,36.18,1008,38,1008,988,8.63,159,13.65,31,1787807235,1787855503,NaN,802,Clouds,partiellement nuageux,03d,"[{'name': ""Les Chênes-lièges d'Ambeille"", 'pri..."
28,carcassonne,43.213036,2.349107,10000,1787833491,32.11,37.96,32.11,33.76,1007,62,1007,979,9.77,60,NaN,98,1787807351,1787855736,NaN,804,Clouds,couvert,04d,"[{'name': 'Tribe Carcassonne', 'price': '€ 286..."
29,ariege,42.945537,1.406554,10000,1787833921,26.90,26.56,25.50,27.36,1009,35,1009,905,1.34,94,8.05,0,1787807601,1787855940,NaN,800,Clear,ciel dégagé,01d,"[{'name': 'Mercure Ax Les Thermes', 'price': '..."
30,toulouse,43.604464,1.444243,10000,1787833357,31.99,33.23,31.99,32.55,1007,45,1007,987,3.60,140,NaN,58,1787807535,1787855989,NaN,803,Clouds,nuageux,04d,[{'name': 'Eklo Hotels Toulouse Cartoucherie Z...
31,montauban,44.017584,1.354999,10000,1787833923,30.56,31.23,30.56,30.56,1008,46,1008,995,2.01,207,3.43,100,1787807520,1787856046,NaN,804,Clouds,couvert,04d,"[{'name': 'Unisotel Montauban EX F1', 'price':..."
32,biarritz,43.471144,-1.552728,10000,1787833924,23.00,23.03,22.55,23.00,1009,64,1009,1003,1.03,0,NaN,100,1787808267,1787856695,0.85,500,Rain,légère pluie,10d,[{'name': 'Nemea Appart Hotel Les Hauts de Mil...
33,bayonne,43.494514,-1.473666,10000,1787833925,23.42,23.49,22.97,24.54,1009,64,1009,1005,1.03,0,NaN,100,1787808246,1787856678,1.41,501,Rain,pluie modérée,10d,"[{'name': 'ibis budget Bayonne', 'price': '€ 1..."
34,la rochelle,46.159732,-1.151595,10000,1787833926,20.21,20.40,20.07,20.74,1010,81,1010,1010,1.54,90,NaN,100,1787807924,1787856846,17.12,503,Rain,très forte pluie,10d,[{'name': 'ibis budget La Rochelle Centre les ...

In [10]:
obs_generales = df.groupby(["weather.0.id", "weather.0.main", "weather.0.description"]).agg({"dt": "count"}).reset_index().rename(columns={"dt": "count"})

In [11]:
obs_generales

   weather.0.id weather.0.main  weather.0.description  count
0           500           Rain           légère pluie      1
1           501           Rain          pluie modérée      1
2           503           Rain       très forte pluie      1
3           800          Clear            ciel dégagé      1
4           802         Clouds  partiellement nuageux      1
5           803         Clouds                nuageux      3
6           804         Clouds                couvert     27

In [12]:
villes_météo_top = []

for i, city in enumerate(df["city"]) : 
  if df["weather.0.id"][i] == 800 : 
    villes_météo_top.append(city)

In [13]:
villes_météo_top

['ariege']

In [14]:
fig = px.bar(obs_generales, x="weather.0.main", y="count", color="weather.0.description", title="Répartition des conditions météorologiques")

In [15]:
fig

In [16]:
fig = go.Figure(data=[go.Scattergeo(
    lon = df['lon'],
    lat = df['lat'],
    text = df['city'],
    mode = 'markers',
    marker = dict(
        size = 8,
        color = df['weather.0.id'],
        colorscale = 'Viridis',
        colorbar_title = "Weather ID"
    )
    )])

In [17]:
fig

In [18]:
df.columns

Index(['city', 'lat', 'lon', 'visibility', 'dt', 'main.temp',
       'main.feels_like', 'main.temp_min', 'main.temp_max', 'main.pressure',
       'main.humidity', 'main.sea_level', 'main.grnd_level', 'wind.speed',
       'wind.deg', 'wind.gust', 'clouds.all', 'sys.sunrise', 'sys.sunset',
       'rain.1h', 'weather.0.id', 'weather.0.main', 'weather.0.description',
       'weather.0.icon', 'hotels'],
      dtype='object')

In [19]:
fig = go.Figure()

In [30]:
fig.add_trace(
    go.Scattermap(
        lat = df["lat"],
        lon = df["lon"],
        mode = "markers",
        marker = dict(
            size = 14,
            color = obs_generales['count'],
            colorscale = "RdYlGn",
            showscale = False,
            opacity = 1,
            colorbar=dict(title="Nombre d'observations", len=0.5, y=0.5)
        ),
        customdata=df[
            ["city", "main.temp", "wind.speed", "weather.0.description", "weather.0.id"]
        ]
    )
)

fig.update_layout(
    map_style ='open-street-map',
    map_center=dict(lat=46.5, lon=2.5),
    map_zoom=4.5,
    height=650,
    margin=dict(l=0, r=0, t=30, b=0)
)

fig.show()