In [1]:
# Import des librairies pour l'EDA de Kayak
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
final_df = pd.read_csv("/Users/nicolasbour/Desktop/Projets_IA /Projets_certif/02_kayak/data/final_data_cleaned.csv")

In [3]:
pd.set_option('display.max_columns', None)
final_df.head(2)

,city,lat,lon,visibility,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,clouds.all,sys.sunrise,sys.sunset,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotel_city,price,latitude,longitude,rate,rate_label,experience
0,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,€ 521,48.596052,-1.500324,"9,8",Exceptionnel,6
1,mont saint michel,48.635954,-1.51146,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.6,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Huisnes-sur-Mer,€ 364,48.621474,-1.447158,"7,5",Bien,2

In [4]:
print(final_df["visibility"].value_counts())

visibility
10000    875
Name: count, dtype: int64

Valeurs nulles : 
    wind.gust = 16 # => pas de rafales de vent enregistrées dans cette zone
    rain.1h = 32 # => pas de précipitations enregistrées dans cette zone
    # => pour ces valeurs, la valeur nulle correspond à un evenment qui n'a pas eu lieu, donc on peut les considérer comme des valeurs valides et les remplacer par 0.

In [5]:
df = final_df.copy()

In [6]:
if "rain.1h" not in df.columns:
    df["rain.1h"] = 0

df["rain.1h"] = df["rain.1h"].fillna(0)

In [7]:
if df["wind.gust"].isnull().any():
    df["wind.gust"] = df["wind.gust"].fillna(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875 entries, 0 to 874
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   875 non-null    object
 1   lat                    875 non-null    float64
 2   lon                    875 non-null    float64
 3   visibility             875 non-null    int64
 4   dt                     875 non-null    int64
 5   main.temp              875 non-null    float64
 6   main.feels_like        875 non-null    float64
 7   main.temp_min          875 non-null    float64
 8   main.temp_max          875 non-null    float64
 9   main.pressure          875 non-null    int64
 10  main.humidity          875 non-null    int64
 11  main.sea_level         875 non-null    int64
 12  main.grnd_level        875 non-null    int64
 13  wind.speed             875 non-null    float64
 14  wind.deg               875 non-null    int64
 15  wind.gust              875 non-null    float64
 16  clouds.all             875 non-null    int64
 17  sys.sunrise            875 non-null    int64
 18  sys.sunset             875 non-null    int64
 19  rain.1h                875 non-null    int64
 20  weather.0.id           875 non-null    int64
 21  weather.0.main         875 non-null    object
 22  weather.0.description  875 non-null    object
 23  weather.0.icon         875 non-null    object
 24  hotel_city             875 non-null    object
 25  price                  875 non-null    object
 26  latitude               875 non-null    float64
 27  longitude              875 non-null    float64
 28  rate                   865 non-null    object
 29  rate_label             865 non-null    object
 30  experience             865 non-null    object
dtypes: float64(10), int64(12), object(9)
memory usage: 212.0+ KB

In [9]:
df

,city,lat,lon,visibility,dt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,clouds.all,sys.sunrise,sys.sunset,rain.1h,weather.0.id,weather.0.main,weather.0.description,weather.0.icon,hotel_city,price,latitude,longitude,rate,rate_label,experience
0,mont saint michel,48.635954,-1.511460,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.60,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,€ 521,48.596052,-1.500324,"9,8",Exceptionnel,6
1,mont saint michel,48.635954,-1.511460,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.60,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Huisnes-sur-Mer,€ 364,48.621474,-1.447158,"7,5",Bien,2
2,mont saint michel,48.635954,-1.511460,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.60,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Huisnes-sur-Mer,€ 1 140,48.619514,-1.459112,"9,7",Exceptionnel,10
3,mont saint michel,48.635954,-1.511460,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.60,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,€ 1 954,48.594490,-1.511429,"8,7",Superbe,152
4,mont saint michel,48.635954,-1.511460,10000,1788426584,20.24,20.49,20.24,20.24,1022,83,1022,1017,4.60,217,6.5,99,1788413148,1788461136,0,804,Clouds,couvert,04d,Beauvoir,€ 440,48.597734,-1.511773,"8,9",Superbe,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,la rochelle,46.159732,-1.151595,10000,1788426301,21.12,21.40,20.52,21.29,1025,81,1025,1025,1.54,0,0.0,7,1788413251,1788460860,0,800,Clear,ciel dégagé,01d,La Rochelle,€ 239,46.155829,-1.148558,"8,5",Très bien,1 008
871,la rochelle,46.159732,-1.151595,10000,1788426301,21.12,21.40,20.52,21.29,1025,81,1025,1025,1.54,0,0.0,7,1788413251,1788460860,0,800,Clear,ciel dégagé,01d,La Rochelle,€ 165,46.169759,-1.121584,"7,9",Bien,3 255
872,la rochelle,46.159732,-1.151595,10000,1788426301,21.12,21.40,20.52,21.29,1025,81,1025,1025,1.54,0,0.0,7,1788413251,1788460860,0,800,Clear,ciel dégagé,01d,La Rochelle,€ 237,46.156145,-1.155469,"8,6",Superbe,72
873,la rochelle,46.159732,-1.151595,10000,1788426301,21.12,21.40,20.52,21.29,1025,81,1025,1025,1.54,0,0.0,7,1788413251,1788460860,0,800,Clear,ciel dégagé,01d,La Rochelle,€ 202,46.154127,-1.147499,"7,8",Bien,2 048
874,la rochelle,46.159732,-1.151595,10000,1788426301,21.12,21.40,20.52,21.29,1025,81,1025,1025,1.54,0,0.0,7,1788413251,1788460860,0,800,Clear,ciel dégagé,01d,La Rochelle,€ 381,46.154707,-1.145806,"8,9",Superbe,42

In [10]:
obs_meteo = df.groupby(["weather.0.id", "weather.0.main", "weather.0.description"]).agg({"dt": "count"}).reset_index().rename(columns={"dt": "count"})

In [11]:
obs_meteo

   weather.0.id weather.0.main  weather.0.description  count
0           800          Clear            ciel dégagé    350
1           801         Clouds            peu nuageux    225
2           802         Clouds  partiellement nuageux    100
3           803         Clouds                nuageux     25
4           804         Clouds                couvert    175

In [12]:
fig = px.bar(obs_meteo, x="weather.0.main", y="count", color="weather.0.description", title="Répartition des conditions météorologiques")

In [13]:
fig

In [14]:
fig = go.Figure(data=[go.Scattergeo(
    lon = df['lon'],
    lat = df['lat'],
    text = df['city'],
    mode = 'markers',
    marker = dict(
        size = 8,
        color = df['weather.0.id'],
        colorscale = 'Viridis',
        colorbar_title = "Weather ID"
    )
    )])

In [15]:
fig

In [16]:
df.columns

Index(['city', 'lat', 'lon', 'visibility', 'dt', 'main.temp',
       'main.feels_like', 'main.temp_min', 'main.temp_max', 'main.pressure',
       'main.humidity', 'main.sea_level', 'main.grnd_level', 'wind.speed',
       'wind.deg', 'wind.gust', 'clouds.all', 'sys.sunrise', 'sys.sunset',
       'rain.1h', 'weather.0.id', 'weather.0.main', 'weather.0.description',
       'weather.0.icon', 'hotel_city', 'price', 'latitude', 'longitude',
       'rate', 'rate_label', 'experience'],
      dtype='object')

In [17]:
# Le dataset contient une ligne par hôtel.
# On conserve une seule ligne par ville pour éviter les doublons sur la carte.
df_map = df.drop_duplicates(subset="city").copy()

fig = go.Figure()

fig.add_trace(
    go.Scattermap(
        lat=df_map["lat"],
        lon=df_map["lon"],
        mode="markers",
        marker=dict(
            size=14,
            color=df_map["weather.0.id"],
            colorscale="RdYlGn",
            showscale=True,
            colorbar=dict(
                title="Conditions météorologiques",
                len=0.8,
            ),
            opacity=0.85,
        ),
        customdata=df_map[
            [
                "city",
                "main.temp",
                "main.feels_like",
                "wind.speed",
                "weather.0.main",
                "weather.0.description",
            ]
        ],
        hovertemplate=(
            "<b>%{customdata[0]}</b><br>"
            "Température : %{customdata[1]:.1f} °C<br>"
            "Ressenti : %{customdata[2]:.1f} °C<br>"
            "Vent : %{customdata[3]:.1f} m/s<br>"
            "Conditions : %{customdata[4]}<br>"
            "Description : %{customdata[5]}"
            "<extra></extra>"
        ),
    )
)

fig.update_layout(
    map=dict(
        style="open-street-map",
        center=dict(lat=46.5, lon=2.5),
        zoom=4.5,
    ),
    height=650,
    title=dict(
        text="Carte des conditions météorologiques en France",
        x=0.5,
        xanchor="center",
        yanchor="top",
    ),
    margin=dict(l=30, r=0, t=30, b=30),
)

fig.update_layout(
    legend=dict(
        title="Conditions météorologiques",
        x=0.01,
        y=0.99,
        bgcolor="rgba(255, 255, 255, 0.7)",
        bordercolor="black",
        borderwidth=1,
    )
)
fig.show()

Définition des critères pour générer le top 5 des villes en fonction de la météo :
    - Pondération des critères : 
        - Température ressentie : 0.2
        - Vitesse du vent : 0.15
        - Rafales de vent : 0.2
        - Visibilité : 0.1
        - Couverture nuageuse : 0.35
    - Précipitations : éliminatoire (si pluie > 0, la ville est éliminée)

    - critères de notation :
        - Température ressentie : 
            - 20°C à 25°C : 1 point
            - 10°C à 19°C : 0.5 point
            - 5°C à 10°C : 0 point
            - <5°C : -1 point
        - Vitesse du vent : 
            - <20 km/h : 1 point
            - 20-40 km/h : 0.5 point
            - >40 km/h : 0 point
        - Rafales de vent : 
            - <20 km/h : 1 point
            - 20-40 km/h : 0.5 point
            - >40 km/h : 0 point
        - Visibilité : 
            - >10 km : 1 point
            - 2-10 km : 0.5 point
            - <2 km : 0 point
        - Couverture_nuageuse (weather_id) : 
            - 800 : 1 point
            - 801-802 : 0.5 point
            - 803-804 : 0 point

In [18]:
df_cws = df[["city", "main.feels_like", "wind.speed", "wind.gust", "rain.1h", "weather.0.id"]]

In [19]:
df_cws = df_cws.drop_duplicates(subset="city")

In [20]:
cities_scores = []

for _,row in df_cws.iterrows():
    city_name = row["city"]
    feeling_temp = row["main.feels_like"]
    wind_speed = row["wind.speed"] * 3.6  # Conversion de m/s en km/h
    wind_gust = row["wind.gust"] * 3.6  # Conversion de m/s en km/h
    rain_1h = row["rain.1h"]
    weather_id = row["weather.0.id"]

    # Calcul du score de température pour chaque ville
    temp_score = 0
    if feeling_temp >= 20 and feeling_temp <= 25:
        temp_score += 1
    elif feeling_temp >= 25 and feeling_temp <= 30:
        temp_score += 0.3
    elif feeling_temp >= 15 and feeling_temp < 20:
        temp_score += 0.5
    elif feeling_temp >= 10 and feeling_temp < 15:
        temp_score += 0.2
    elif feeling_temp >= 5 and feeling_temp < 10:
        temp_score += 0
    elif feeling_temp < 5 or feeling_temp > 30:
        temp_score -= 1

    wind_speed_score = 0
    if wind_speed <= 10:
        wind_speed_score += 1
    elif wind_speed > 10 and wind_speed <= 20:
        wind_speed_score += 0.5
    elif wind_speed >20 and wind_speed <= 30:
        wind_speed_score += 0.3
    elif wind_speed > 30 and wind_speed <= 40:
        wind_speed_score += 0
    elif wind_speed > 40:
        wind_speed_score -= 1

    wind_gust_score = 0
    if wind_gust == 0:
        wind_gust_score += 1
    elif wind_gust > 0 and wind_gust <= 20:
        wind_gust_score += 0.5
    elif wind_gust > 20 and wind_gust <= 30:
        wind_gust_score += 0.3
    elif wind_gust > 30 and wind_gust <= 40:
        wind_gust_score += 0
    elif wind_gust > 40:
        wind_gust_score -= 1

    rain_1h_score = 0
    if rain_1h != 0:
        rain_1h_score -= 10

    cloud_score = 0
    if weather_id == 800:
        cloud_score += 1
    elif weather_id == 801 :
        cloud_score += 0.7
    elif weather_id == 802:
        cloud_score += 0.5
    elif weather_id == 803 :
        cloud_score += 0.3
    elif weather_id == 804:
        cloud_score += 0

    # Calcul du score total pondéré pour chaque ville
    total_score = (
        0.2 * temp_score
        + 0.15 * wind_speed_score
        + 0.2 * wind_gust_score
        + 0.1 * rain_1h_score
        + 0.35 * cloud_score
        )

    cities_scores.append({"city": city_name, "temp_score": temp_score, "wind_speed_score": wind_speed_score, "wind_gust_score": wind_gust_score, "rain_1h_score": rain_1h_score, "cloud_score": cloud_score, "total_score": total_score})

In [21]:
cities_scores_df = pd.DataFrame(cities_scores, columns=["city", "temp_score", "wind_speed_score", "wind_gust_score", "rain_1h_score", "cloud_score", "total_score"])

In [22]:
cities_scores_df

,city,temp_score,wind_speed_score,wind_gust_score,rain_1h_score,cloud_score,total_score
0,mont saint michel,1.0,0.5,0.3,0,0.0,0.335
1,saint malo,1.0,0.3,1.0,0,0.0,0.445
2,bayeux,1.0,0.3,0.0,0,0.0,0.245
3,le havre,1.0,0.3,1.0,0,0.0,0.445
4,rouen,1.0,0.3,1.0,0,0.0,0.445
5,paris,1.0,0.5,1.0,0,0.3,0.580
6,amiens,1.0,0.3,0.0,0,0.0,0.245
7,lille,1.0,0.3,1.0,0,0.0,0.445
8,strasbourg,1.0,1.0,1.0,0,0.5,0.725
9,chateau du haut koenigsbourg,1.0,1.0,1.0,0,0.5,0.725
10,colmar,1.0,0.5,0.3,0,0.5,0.510
11,eguisheim,1.0,0.5,0.3,0,0.7,0.580
12,besancon,1.0,1.0,0.5,0,1.0,0.800
13,dijon,1.0,1.0,1.0,0,0.7,0.795
14,annecy,1.0,1.0,1.0,0,1.0,0.900
15,grenoble,0.3,1.0,0.5,0,1.0,0.660
16,lyon,0.3,1.0,1.0,0,1.0,0.760
17,gorges du verdon,1.0,1.0,0.5,0,0.7,0.695
18,bormes les mimosas,0.3,0.5,1.0,0,0.7,0.580
19,cassis,0.3,1.0,0.5,0,1.0,0.660
20,marseille,0.3,0.5,0.3,0,1.0,0.545
21,aix en provence,0.3,1.0,0.5,0,0.7,0.555
22,avignon,0.3,0.0,1.0,0,1.0,0.610
23,uzes,0.3,0.3,0.0,0,1.0,0.455
24,nimes,0.3,0.3,1.0,0,1.0,0.655
25,aigues mortes,0.3,0.3,1.0,0,0.7,0.550
26,saintes maries de la mer,0.3,0.5,0.3,0,0.7,0.440
27,collioure,-1.0,0.5,0.3,0,0.7,0.180
28,carcassonne,0.3,0.3,1.0,0,1.0,0.655
29,ariege,0.5,1.0,0.5,0,1.0,0.700
30,toulouse,1.0,1.0,1.0,0,0.5,0.725
31,montauban,1.0,1.0,0.5,0,0.7,0.695
32,biarritz,1.0,1.0,1.0,0,1.0,0.900
33,bayonne,1.0,1.0,1.0,0,1.0,0.900
34,la rochelle,1.0,1.0,1.0,0,1.0,0.900

In [27]:
top_5_cities = (
    cities_scores_df
    .sort_values("total_score", ascending=False)
    .head(5)
)

top_5_cities

,city,temp_score,wind_speed_score,wind_gust_score,rain_1h_score,cloud_score,total_score
34,la rochelle,1.0,1.0,1.0,0,1.0,0.9
33,bayonne,1.0,1.0,1.0,0,1.0,0.9
32,biarritz,1.0,1.0,1.0,0,1.0,0.9
14,annecy,1.0,1.0,1.0,0,1.0,0.9
12,besancon,1.0,1.0,0.5,0,1.0,0.8

In [24]:
top_5_cities = pd.merge(top_5_cities, df[["city", "lat", "lon"]], on="city", how="left")

In [25]:
fig = go.Figure(
    go.Scattermap(
        lat=top_5_cities["lat"],
        lon=top_5_cities["lon"],
        text=top_5_cities["city"],
        mode="markers+text",
        textposition="top center",
        marker=dict(
            size=14,
            color=top_5_cities["total_score"],
            colorscale="Viridis",
            showscale=True,
            colorbar=dict(
                title="Score météo"
            ),
        ),
        hovertemplate=(
            "<b>%{text}</b><br>"
            "Score météo : %{marker.color:.2f}<br>"
            "<extra></extra>"
        ),
    )
)

fig.update_layout(
    map=dict(
        style="open-street-map",
        center=dict(
            lat=46.5,
            lon=2.5,
        ),
        zoom=4.5,
    ),
    height=650,
    margin=dict(l=30, r=30, t=70, b=30),
    title=dict(
        text="Top 5 des villes avec les meilleures conditions météorologiques",
        x=0.5,
        xanchor="center",
    ),
)

fig.show()

Le top 5 des villles est défini en fontction de la météo. Les critères de notation sont pondérés pour obtenir un score total pour chaque ville. Les villes avec des précipitations sont éliminées du classement. Le top 5 des villes est ensuite affiché sur une carte avec leurs coordonnées géographiques (latitude et longitude).

!!! Un nouvel affinage des critères de notation et de pondération peut être effectué pour obtenir un classement plus précis et éviter les scores égaux risquant de fausser le classement du top 5. !!!